# -*- coding: utf-8 -*-
"""Dane językowe programu „Czytam sylabami". Autorskie, nie generowane.

Kolejność spółgłosek: trudność artykulacyjna + odróżnialność kształtu,
nie alfabet. Sylaby otwarte do tygodnia 7, sylaba zamknięta w 8.
Litery z diakrytykami wchodzą tam, gdzie są potrzebne do czytanek:
Ł w 7, Ó w 8, F/H w 10, miękkie Ś Ć Ź Ń w 11, nosowe Ą Ę w 12.
"""

SAMOGLOSKI = ["A", "O", "U", "I", "E", "Y"]

# Sylaby otwarte — zestaw samogłosek per spółgłoska. Pomijamy połączenia,
# których w polszczyźnie nie ma (TI, DI, KY, GY).
OTWARTE = {
    "M": "A O U I E Y", "P": "A O U I E Y", "L": "A O U I E Y", "B": "A O U I E Y",
    "T": "A O U E Y",   "D": "A O U E Y",   "K": "A O U I E", "N": "A O U I E Y",
    "S": "A O U I E Y", "W": "A O U I E Y", "Ł": "A O U E Y",
    "Z": "A O U I E Y", "C": "A O U I E Y", "G": "A O U I E", "J": "A O U E",
    "R": "A O U I E Y", "F": "A O U I E",   "H": "A O U E",
    "SZ": "A O U E Y",  "CZ": "A O U E Y",  "Ż": "A O U E",
    "CH": "A O U E Y",  "RZ": "A O U E Y",  "DZ": "A O E",
}


def syl(*spolgloski):
    out = []
    for s in spolgloski:
        out += [s + v for v in OTWARTE[s].split()]
    return out


TYGODNIE = [
    # ---------------------------------------------------------------- 1
    dict(
        nr=1, poziom=1,
        cel="W tym tygodniu dziecko rozpoznaje sześć samogłosek i słyszy je na początku wyrazu.",
        litery=SAMOGLOSKI, sylaby=SAMOGLOSKI, wyrazy=[],
        opis="Sześć samogłosek. Jeszcze nie czytamy sylab — słuchamy i rozpoznajemy.",
        powtorka_z=[], powtorka_syl=[], powtorka_wyr=[],
        zdania=[],
        czytanka=dict(
            tytul="Jak otwierają się usta",
            czyta="rodzic",
            linie=["A — usta otwarte szeroko.", "O — usta jak małe kółko.",
                   "U — usta jak dzióbek.", "I — usta jak uśmiech.",
                   "E — usta otwarte w połowie.", "Y — usta jak przy zdziwieniu."],
            pytania=["Przy której samogłosce usta są najszersze?",
                     "Powiedz A i O na zmianę. Co robią usta?"]),
        gra=dict(
            nazwa="Łowca samogłosek",
            cel="Usłyszeć samogłoskę na początku wyrazu.",
            gracze="2 osoby", czas=10,
            przygotowanie=["Wytnij sześć kart z samogłoskami ze strony obok.",
                           "Rozłóż je przed dzieckiem obrazkiem do góry."],
            zasady=["Mówisz wyraz: ANANAS, OKO, UCHO, IGŁA, EKRAN, YETI.",
                    "Dziecko podnosi kartę z samogłoską, którą usłyszało na początku.",
                    "Za trafienie karta zostaje u dziecka. Wygrywa, kto zbierze wszystkie sześć.",
                    "Jeśli dziecko się myli, powiedz wyraz jeszcze raz, przeciągając pierwszą głoskę: AAAnanas."],
            elementy=["6 kart z samogłoskami A O U I E Y"]),
        karta_rodzica=dict(
            co_powiedziec=["„Posłuchaj, jak zaczyna się to słowo.”",
                           "„Powiedz to razem ze mną: AAA.”",
                           "„Pokaż palcem literę, którą słyszysz.”"],
            na_co_uwazac=["Nie mów nazw liter („em”, „be”). Mów same głoski: A, O, U.",
                          "Dziecko może mylić I z Y. To normalne w tym tygodniu.",
                          "Dziesięć minut dziennie wystarczy. Więcej nie przyspieszy."],
            kiedy_dalej=["Dziecko rozpoznaje wszystkie sześć samogłosek na początku wyrazu.",
                         "Nie musi ich jeszcze pisać ładnie ani z pamięci."],
            jesli_nie_idzie=["Zostań przy trzech: A, O, U. Resztę dołóż w przyszłym tygodniu.",
                             "Powtórz ten tydzień. Program nie ma terminu."]),
    ),
    # ---------------------------------------------------------------- 2
    dict(
        nr=2, poziom=2,
        cel="Dziecko czyta pierwsze sylaby otwarte z M i składa z nich wyraz MAMA.",
        litery=["M"], sylaby=syl("M"), wyrazy=["MAMA", "MAMY", "MIMO"],
        opis="Pierwsza spółgłoska. M jest najłatwiejsza — widać ją na ustach i da się ją przeciągnąć.",
        powtorka_z=[1], powtorka_syl=SAMOGLOSKI, powtorka_wyr=[],
        zdania=[],
        czytanka=dict(
            tytul="Mama", czyta="dziecko",
            linie=["MA MA", "MA MO MU", "MAMA", "MAMA MA", "MAMY"],
            pytania=["Pokaż palcem sylabę MA.", "Ile razy widzisz MA w słowie MAMA?"]),
        gra=dict(
            nazwa="Sylabowe domino",
            cel="Przeczytać sylabę i dopasować ją do takiej samej.",
            gracze="2 osoby", czas=10,
            przygotowanie=["Wytnij dwanaście kostek domina ze strony obok.",
                           "Rozdajcie po sześć, resztę zostawcie na stosie."],
            zasady=["Kładziecie na zmianę kostkę tak, żeby sylaba pasowała do sylaby na końcu rzędu.",
                    "Kładąc kostkę, trzeba przeczytać sylabę na głos.",
                    "Kto nie ma pasującej kostki, dobiera ze stosu.",
                    "Wygrywa ten, kto pierwszy pozbędzie się wszystkich kostek."],
            elementy=["12 kostek domina z sylabami MA MO MU MI ME MY"]),
        karta_rodzica=dict(
            co_powiedziec=["„Czytamy całą sylabę naraz, nie po literce.”",
                           "„M i A to razem MA.”",
                           "„Przesuń palcem pod sylabą i powiedz ją jednym tchem.”"],
            na_co_uwazac=["Nie pozwól literować („em-a-em-a”). To wraca potem jako czytanie po literze.",
                          "Jeśli dziecko czyta wolno, ale poprawnie — jest dobrze.",
                          "MY i MI brzmią podobnie. Pokaż różnicę w ułożeniu ust."],
            kiedy_dalej=["Dziecko czyta wszystkie sześć sylab bez literowania.",
                         "Przeczytało MAMA jako dwa kawałki, nie cztery."],
            jesli_nie_idzie=["Zakryj drugą sylabę kartką i czytajcie tylko pierwszą.",
                             "Wróć do samogłosek na jeden dzień, potem spróbuj jeszcze raz."]),
    ),
    # ---------------------------------------------------------------- 3
    dict(
        nr=3, poziom=3,
        cel="Dziecko czyta sylaby z P i składa wyrazy z dwóch różnych sylab.",
        litery=["P"], sylaby=syl("P"), wyrazy=["MAPA", "PAPA", "PUMA"],
        opis="Druga spółgłoska. P jest widoczna na ustach tak samo jak M, ale bez głosu.",
        powtorka_z=[1, 2], powtorka_syl=syl("M"), powtorka_wyr=["MAMA", "MAMY"],
        zdania=[],
        czytanka=dict(
            tytul="Mapa", czyta="dziecko",
            linie=["PA PO PU", "MA PA", "MAPA", "PAPA", "PUMA", "MAPA I PUMA"],
            pytania=["Które słowo ma sylabę PU?", "Pokaż dwa słowa, które zaczynają się na PA."]),
        gra=dict(
            nazwa="Sylabowe memory",
            cel="Znaleźć dwie takie same sylaby i przeczytać je na głos.",
            gracze="2 osoby", czas=12,
            przygotowanie=["Wytnij dwadzieścia cztery karty ze strony obok.",
                           "Rozłóż je zakryte, sześć na sześć."],
            zasady=["Odkrywasz dwie karty i czytasz obie sylaby na głos.",
                    "Jeśli są takie same, zabierasz parę i grasz dalej.",
                    "Jeśli nie — zakrywasz je w tym samym miejscu.",
                    "Wygrywa ten, kto zbierze więcej par."],
            elementy=["24 karty: po dwie z każdą sylabą MA MO MU MI ME MY PA PO PU PI PE PY"]),
        karta_rodzica=dict(
            co_powiedziec=["„Pierwsza sylaba, druga sylaba, a teraz obie razem.”",
                           "„Co to za słowo?”",
                           "„Zasłoń palcem drugą sylabę. Co zostało?”"],
            na_co_uwazac=["Dziecko może przeczytać MAPA jako MAMA — to zgadywanie z pamięci. Poproś o drugą sylabę osobno.",
                          "P i B jeszcze się nie mylą, bo B wchodzi dopiero w tygodniu 4.",
                          "Nie poprawiaj wymowy. Poprawiaj tylko czytanie."],
            kiedy_dalej=["Dziecko czyta sylaby z M i P wymieszane, nie po kolei.",
                         "Złożyło samodzielnie przynajmniej dwa wyrazy z listy."],
            jesli_nie_idzie=["Wróć do tabeli sylab i czytaj ją w poprzek, nie wierszami.",
                             "Rozłóż tydzień na dwa. Nikt nie liczy."]),
    ),
    # ---------------------------------------------------------------- 4
    dict(
        nr=4, poziom=4,
        cel="Dziecko czyta pierwsze zdanie złożone z wyrazów, które zna.",
        litery=["L", "B"], sylaby=syl("L", "B"),
        wyrazy=["ALA", "OLA", "ULA", "LALA", "LUPA", "BABA", "POLE", "BALE"],
        opis="Dwie spółgłoski naraz i pierwsze zdanie. Od teraz czytamy zdania co tydzień.",
        powtorka_z=[2, 3], powtorka_syl=syl("M", "P"), powtorka_wyr=["MAMA", "MAPA", "PUMA"],
        zdania=["ALA MA LALE.", "OLA MA BALE.", "ULA MA LUPY.", "MAMA MA MAPY."],
        czytanka=dict(
            tytul="Ala i Ola", czyta="dziecko",
            linie=["ALA MA LALE.", "OLA MA BALE.", "ULA MA LUPY.",
                   "MAMA MA MAPY.", "ALA I OLA."],
            pytania=["Kto ma lale?", "Kto ma lupy?", "Ile osób jest w tej czytance?"]),
        gra=dict(
            nazwa="Wyścig po sylabach",
            cel="Przeczytać sylabę, na której stanął pionek.",
            gracze="2–4 osoby", czas=15,
            przygotowanie=["Wytnij planszę, cztery pionki i kostkę ze strony obok.",
                           "Sklej kostkę wzdłuż zakładek."],
            zasady=["Rzucasz kostką i przesuwasz pionek o tyle pól.",
                    "Czytasz na głos sylabę z pola, na którym stanąłeś.",
                    "Jeśli nie przeczytasz, cofasz się o jedno pole.",
                    "Wygrywa ten, kto pierwszy dojdzie do mety."],
            elementy=["plansza 24 pola z sylabami", "4 pionki do złożenia", "kostka do sklejenia"]),
        karta_rodzica=dict(
            co_powiedziec=["„Przeczytaj całe zdanie, potem powiedz je jeszcze raz szybciej.”",
                           "„O kim jest to zdanie?”",
                           "„Kropka na końcu znaczy, że tu robimy przerwę.”"],
            na_co_uwazac=["Pierwsze zdanie bywa szokiem. Przeczytaj je najpierw sam, potem razem, dopiero potem dziecko samo.",
                          "B i P mają ten sam kształt obrócony. Mylenie ich w tym tygodniu jest normalne.",
                          "Nie każ czytać z ekspresją. Na razie liczy się tylko poprawność."],
            kiedy_dalej=["Dziecko przeczytało samo przynajmniej dwa zdania z czytanki.",
                         "Rozróżnia B i L w tabeli sylab."],
            jesli_nie_idzie=["Czytajcie na zmianę: ty jedno zdanie, dziecko następne.",
                             "Zostaw B na przyszły tydzień, ćwicz samo L."]),
    ),
    # ---------------------------------------------------------------- 5
    dict(
        nr=5, poziom=5,
        cel="Dziecko czyta zdania z czasownikiem i rozpoznaje, kto co robi.",
        litery=["T", "D"], sylaby=syl("T", "D"),
        wyrazy=["TATA", "DATA", "LATA", "DOMY", "LOTY", "BUTY", "TUBA", "LODY"],
        opis="T i D różnią się tylko głosem. Ćwiczymy je obok siebie, żeby dziecko usłyszało różnicę.",
        powtorka_z=[3, 4], powtorka_syl=syl("P", "L", "B"),
        powtorka_wyr=["ALA", "OLA", "LALA", "LUPA", "MAPA"],
        zdania=["TO TATA.", "TATA MA BUTY.", "ALA MA LODY.", "TO MAMA.", "MAMA MA MAPY."],
        czytanka=dict(
            tytul="Tata ma buty", czyta="dziecko",
            linie=["TO TATA.", "TATA MA BUTY.", "ALA MA LODY.",
                   "TO MAMA.", "MAMA MA MAPY.", "TATA I MAMA."],
            pytania=["Kto ma buty?", "Kto ma lody?", "Przeczytaj zdanie, w którym jest MAMA."]),
        gra=dict(
            nazwa="T czy D",
            cel="Usłyszeć różnicę między T i D.",
            gracze="2 osoby", czas=10,
            przygotowanie=["Wytnij dwie duże karty: jedną z T, drugą z D.",
                           "Połóż je przed dzieckiem."],
            zasady=["Mówisz sylabę: TA, DA, TO, DO, TU, DU, TE, DE, TY, DY.",
                    "Dziecko klepie w kartę z literą, którą usłyszało.",
                    "Za pięć trafień z rzędu dziecko zamienia się z tobą rolami.",
                    "Podpowiedź: przy D gardło drga. Połóż palce na szyi i sprawdźcie."],
            elementy=["2 duże karty: T i D"]),
        karta_rodzica=dict(
            co_powiedziec=["„Kto to robi? Pokaż palcem.”",
                           "„Przeczytaj jeszcze raz, tym razem bez zatrzymania.”",
                           "„Połóż palec na szyi. Czujesz, że przy D coś drga?”"],
            na_co_uwazac=["T i D to najczęstsza pomyłka w tym tygodniu. Nie jest to powód do niepokoju.",
                          "Jeśli dziecko czyta poprawnie, ale bardzo wolno, nie popędzaj. Tempo przyjdzie samo.",
                          "Pięć zdań dziennie to dużo. Trzy wystarczą."],
            kiedy_dalej=["Dziecko czyta wszystkie zdania z czytanki bez pomocy.",
                         "Odpowiada na pytanie „kto?” po jednym przeczytaniu."],
            jesli_nie_idzie=["Ćwicz samo T przez trzy dni, dopiero potem dołóż D.",
                             "Wróć do wyrazów dwusylabowych, zostaw zdania na później."]),
    ),
    # ---------------------------------------------------------------- 6
    dict(
        nr=6, poziom=6,
        cel="Dziecko czyta wyrazy z czterech różnych spółgłosek bez zatrzymywania się.",
        litery=["K", "N"], sylaby=syl("K", "N"),
        wyrazy=["KINO", "KOTY", "KUNA", "NUTA", "MAKI", "PANI", "NOTA", "TANI"],
        opis="K i N. Po tym tygodniu dziecko ma osiem spółgłosek i czyta większość sylab otwartych.",
        powtorka_z=[4, 5], powtorka_syl=syl("L", "B", "T", "D"),
        powtorka_wyr=["TATA", "BUTY", "LODY", "LALA", "DOMY"],
        zdania=["TO KINO.", "PANI MA KOTY.", "TATA MA NUTY.", "ALA MA MAKI."],
        czytanka=dict(
            tytul="Kino", czyta="dziecko",
            linie=["TO KINO.", "PANI MA KOTY.", "TATA MA NUTY.",
                   "ALA MA MAKI.", "KINO I KOTY."],
            pytania=["Kto ma koty?", "Co ma tata?", "Które słowo ma sylabę KU?"]),
        gra=dict(
            nazwa="Sylabowe bingo",
            cel="Znaleźć na planszy sylabę, którą się usłyszało.",
            gracze="2–4 osoby", czas=12,
            przygotowanie=["Wytnij cztery plansze bingo i żetony ze strony obok.",
                           "Każdy bierze jedną planszę."],
            zasady=["Czytasz sylabę z listy pod planszami.",
                    "Kto ma ją na planszy, zakrywa pole żetonem.",
                    "Zakrywając pole, trzeba przeczytać sylabę na głos.",
                    "Wygrywa ten, kto pierwszy zakryje cały rząd."],
            elementy=["4 plansze bingo 3×3", "36 żetonów", "lista sylab dla prowadzącego"]),
        karta_rodzica=dict(
            co_powiedziec=["„Czytaj dalej, nie zatrzymuj się na trudnej sylabie.”",
                           "„Dobrze. Teraz to samo, ale szybciej.”",
                           "„Które słowo było najtrudniejsze? Przeczytaj je jeszcze raz.”"],
            na_co_uwazac=["To jest połowa programu. Jeśli tu jest dobrze, dalej też będzie.",
                          "KI i NI brzmią miękko. Nie poprawiaj, jeśli dziecko mówi „ki” zamiast „kji”.",
                          "Dziecko może być znudzone. Zmień kolejność stron, nie treść."],
            kiedy_dalej=["Dziecko czyta wyrazy z listy w losowej kolejności.",
                         "Nie zgaduje po pierwszej sylabie."],
            jesli_nie_idzie=["Zrób tydzień przerwy od nowego materiału. Graj w gry z tygodni 2–5.",
                             "Wróć do tabeli powtórkowej i czytaj ją codziennie przez pięć minut."]),
    ),
    # ---------------------------------------------------------------- 7
    dict(
        nr=7, poziom=7,
        cel="Dziecko czyta sylaby z Ł i rozróżnia je od L.",
        litery=["S", "W", "Ł"], sylaby=syl("S", "W", "Ł"),
        wyrazy=["SOWA", "WATA", "SANIE", "NOSI", "KOSI", "WISI", "MAŁA", "BYŁA"],
        opis="S, W i Ł. Ł wchodzi tutaj, bo bez niego nie da się napisać połowy polskich zdań.",
        powtorka_z=[5, 6], powtorka_syl=syl("T", "D", "K", "N"),
        powtorka_wyr=["KINO", "KOTY", "NUTA", "BUTY", "TATA"],
        zdania=["TO SOWA.", "SOWA WISI.", "OLA KOSI.", "MAŁA ALA.", "TATA NOSI SANIE."],
        czytanka=dict(
            tytul="Sowa", czyta="dziecko",
            linie=["TO SOWA.", "SOWA WISI.", "OLA KOSI.",
                   "MAŁA ALA.", "TATA NOSI SANIE.", "SOWA I ALA."],
            pytania=["Co robi sowa?", "Kto nosi sanie?", "Znajdź słowo z Ł."]),
        gra=dict(
            nazwa="L czy Ł",
            cel="Zobaczyć różnicę między L i Ł i nie mylić ich w czytaniu.",
            gracze="2 osoby", czas=10,
            przygotowanie=["Wytnij szesnaście kart z sylabami ze strony obok.",
                           "Podziel je na dwa stosy: L i Ł."],
            zasady=["Bierzesz kartę ze wspólnego stosu i czytasz sylabę.",
                    "Kładziesz ją na właściwym stosie: L albo Ł.",
                    "Za pomyłkę karta wraca na spód stosu.",
                    "Gra kończy się, kiedy stos wspólny się skończy."],
            elementy=["16 kart: LA LO LU LI LE LY ŁA ŁO ŁU ŁE ŁY plus powtórki"]),
        karta_rodzica=dict(
            co_powiedziec=["„Ł mówimy jak angielskie w. Spróbuj: ŁA.”",
                           "„L to język przy zębach. Ł to same usta.”",
                           "„Przeczytaj oba i posłuchaj różnicy.”"],
            na_co_uwazac=["Ł ma kreskę. Dziecko będzie ją gubić przy pisaniu — to normalne.",
                          "Nie wprowadzaj jeszcze Ó ani Ą. Przyjdą w swoim czasie.",
                          "Trzy nowe litery to dużo. Rozłóż ten tydzień na dziesięć dni, jeśli trzeba."],
            kiedy_dalej=["Dziecko czyta L i Ł bez mylenia w tabeli sylab.",
                         "Przeczytało samo całą czytankę."],
            jesli_nie_idzie=["Zostaw Ł na osobny tydzień. S i W wystarczą.",
                             "Pisz Ł zawsze w tym samym kolorze, żeby kreska rzucała się w oczy."]),
    ),
    # ---------------------------------------------------------------- 8
    dict(
        nr=8, poziom=8,
        cel="Dziecko czyta sylabę zamkniętą spółgłoską: KOT, DOM, LAS.",
        litery=["Ó"],
        sylaby=["AM", "OM", "UM", "EM", "YM", "AL", "OL", "UL", "EL",
                "AS", "OS", "US", "ES", "AT", "OT", "UT", "ET",
                "AK", "OK", "UK", "EK", "AN", "ON", "UN", "EN"],
        wyrazy=["KOT", "DOM", "LAS", "NOS", "MAK", "SOK", "SEN", "DÓŁ",
                "KOTEK", "DOMEK", "LASEK", "NOSEK"],
        opis="Najważniejszy tydzień programu. Sylaba przestaje kończyć się samogłoską. "
             "Dochodzi też Ó, które czyta się jak U.",
        powtorka_z=[6, 7], powtorka_syl=syl("K", "N", "S", "W"),
        powtorka_wyr=["SOWA", "WATA", "KINO", "MAŁA", "NOSI"],
        zdania=["TO KOT.", "KOT MA DOM.", "TAM MAK I LAS.", "KOTEK MA DOMEK."],
        czytanka=dict(
            tytul="Kot ma dom", czyta="dziecko",
            linie=["TO KOT.", "KOT MA DOM.", "TAM MAK I LAS.",
                   "KOTEK MA DOMEK.", "KOT I KOTEK."],
            pytania=["Co ma kot?", "Które słowo kończy się na T?",
                     "Czym różni się KOT od KOTEK?"]),
        gra=dict(
            nazwa="Domknij sylabę",
            cel="Dołożyć spółgłoskę na końcu sylaby i przeczytać nowy wyraz.",
            gracze="2 osoby", czas=15,
            przygotowanie=["Wytnij karty z sylabami otwartymi i karty z pojedynczymi spółgłoskami.",
                           "Ułóż je w dwóch stosach."],
            zasady=["Bierzesz kartę z sylabą, np. KO, i kładziesz ją na stole.",
                    "Dokładasz kartę ze spółgłoską, np. T. Powstaje KOT.",
                    "Czytasz na głos to, co powstało.",
                    "Jeśli wyszedł prawdziwy wyraz, zabierasz obie karty. Jeśli nie — wracają na spód."],
            elementy=["18 kart z sylabami otwartymi", "8 kart ze spółgłoskami T K S M N L Ł D"]),
        karta_rodzica=dict(
            co_powiedziec=["„Najpierw KO, potem dokładamy T. Razem: KOT.”",
                           "„Zasłoń ostatnią literę. Co zostało?”",
                           "„Teraz odsłoń. Co się zmieniło?”"],
            na_co_uwazac=["To jest miejsce, w którym zacina się większość dzieci. Spodziewaj się tego i nie panikuj.",
                          "Dziecko może czytać KOT jako KO-TE, dokładając samogłoskę. Pokaż, że po T nic już nie ma.",
                          "Jeśli utknęliście na dłużej niż dwa tygodnie, jest osobny materiał: „Sylaby zamknięte — dogrywka”.",
                          "Ó czytamy tak samo jak U. Nie tłumacz dlaczego — na razie wystarczy, że tak jest."],
            kiedy_dalej=["Dziecko czyta pięć wyrazów jednosylabowych bez dokładania samogłoski na końcu.",
                         "Przeczytało KOTEK jako dwie sylaby."],
            jesli_nie_idzie=["Zostań w tym tygodniu tak długo, jak trzeba. To nie jest opóźnienie.",
                             "Ćwicz tylko wyrazy z T na końcu, potem tylko z K. Po jednej spółgłosce."]),
    ),
    # ---------------------------------------------------------------- 9
    dict(
        nr=9, poziom=9,
        cel="Dziecko czyta wyrazy trzysylabowe.",
        litery=["Z", "C", "G", "J"], sylaby=syl("Z", "C", "G", "J"),
        wyrazy=["ZUPA", "KOZA", "WAZA", "NOGA", "GUMA", "ZIMA", "CENA",
                "JAGODA", "GAZETA", "JAJKO"],
        opis="Cztery spółgłoski i pierwsze wyrazy trzysylabowe.",
        powtorka_z=[7, 8], powtorka_syl=["AM", "OT", "EK", "AS", "ON"] + syl("S", "W"),
        powtorka_wyr=["KOT", "DOM", "LAS", "SOWA", "DOMEK"],
        zdania=["TO KOZA.", "KOZA MA NOGI.", "TO JEST ZUPA.", "ALA JE JAGODY."],
        czytanka=dict(
            tytul="Koza", czyta="dziecko",
            linie=["TO KOZA.", "KOZA MA NOGI.", "TO JEST ZUPA.",
                   "ALA JE JAGODY.", "GAZETA I GUMA."],
            pytania=["Co ma koza?", "Co je Ala?", "Znajdź słowo z trzema sylabami."]),
        gra=dict(
            nazwa="Trzy sylaby",
            cel="Złożyć wyraz z trzech kart i przeczytać go w całości.",
            gracze="2–3 osoby", czas=15,
            przygotowanie=["Wytnij karty sylabowe ze strony obok.",
                           "Rozłóż je odkryte na stole."],
            zasady=["Szukasz trzech kart, które razem tworzą wyraz, np. JA-GO-DA.",
                    "Układasz je w rzędzie i czytasz cały wyraz na głos.",
                    "Za poprawny wyraz zabierasz karty.",
                    "Wygrywa ten, kto ułoży więcej wyrazów. Lista jest w kluczu odpowiedzi."],
            elementy=["30 kart sylabowych", "lista możliwych wyrazów dla rodzica"]),
        karta_rodzica=dict(
            co_powiedziec=["„Ten wyraz ma trzy kawałki. Przeczytaj każdy osobno.”",
                           "„Teraz wszystkie trzy pod rząd, bez przerwy.”",
                           "„Klaśnij tyle razy, ile jest sylab.”"],
            na_co_uwazac=["Trzy sylaby to skok. Dziecko może gubić środkową — zasłoń pierwszą, żeby zobaczyło resztę.",
                          "ZI, CI, NI czytamy miękko. Nie rozkładaj tego na czynniki, dziecko usłyszy samo.",
                          "J jest łatwe. Wykorzystaj je, żeby podnieść dziecku humor po tygodniu 8."],
            kiedy_dalej=["Dziecko czyta trzy wyrazy trzysylabowe bez pomocy.",
                         "Nadal poprawnie czyta wyrazy zamknięte z tygodnia 8."],
            jesli_nie_idzie=["Wróć do dwóch sylab na tydzień. Trzecia poczeka.",
                             "Dziel wyrazy ołówkiem na sylaby przed czytaniem."]),
    ),
    # ---------------------------------------------------------------- 10
    dict(
        nr=10, poziom=10,
        cel="Dziecko czyta dwuznaki jako jeden dźwięk, nie dwie litery.",
        litery=["SZ", "CZ", "Ż", "RZ", "CH", "DZ", "F", "H"],
        sylaby=syl("SZ", "CZ", "Ż", "CH") + ["DZA", "DZO", "DZE", "FA", "FO", "HA", "HO"],
        wyrazy=["SZAFA", "ŻABA", "CHATA", "MUCHA", "KOSZ", "CZAS", "ŻUK",
                "CZAPKA", "DACH", "FOTEL"],
        opis="Dwuznaki: dwie litery, jeden dźwięk. Plus F i H, żeby domknąć alfabet.",
        powtorka_z=[8, 9], powtorka_syl=syl("Z", "C", "G", "J"),
        powtorka_wyr=["KOZA", "ZUPA", "JAGODA", "KOT", "DOMEK"],
        zdania=["TO ŻABA.", "TO SZAFA.", "W SZAFIE JEST KOSZ.", "MUCHA MA CZAS."],
        czytanka=dict(
            tytul="Żaba i szafa", czyta="dziecko",
            linie=["TO ŻABA.", "TO SZAFA.", "W SZAFIE JEST KOSZ.",
                   "MUCHA MA CZAS.", "ŻUK I ŻABA."],
            pytania=["Co jest w szafie?", "Znajdź słowo z SZ.",
                     "Ile liter ma dźwięk CZ? A ile znaków?"]),
        gra=dict(
            nazwa="Dwie litery, jeden dźwięk",
            cel="Rozpoznać dwuznak i nie czytać go po literze.",
            gracze="2 osoby", czas=12,
            przygotowanie=["Wytnij karty z dwuznakami: SZ, CZ, RZ, CH, DZ.",
                           "Wytnij karty z wyrazami ze strony obok."],
            zasady=["Odkrywasz kartę z wyrazem i czytasz go na głos.",
                    "Wskazujesz w nim dwuznak i kładziesz na nim odpowiednią kartę.",
                    "Za poprawne wskazanie bierzesz punkt.",
                    "Kto pierwszy ma dziesięć punktów, wygrywa."],
            elementy=["5 kart z dwuznakami", "20 kart z wyrazami"]),
        karta_rodzica=dict(
            co_powiedziec=["„SZ to jeden dźwięk, chociaż są dwie litery.”",
                           "„Nie czytaj es-zet. Czytaj SZ.”",
                           "„Pokaż palcem obie litery naraz.”"],
            na_co_uwazac=["Dziecko będzie czytać S-Z osobno. Zakryj obie litery jednym palcem, żeby widziało je jako całość.",
                          "RZ i Ż brzmią tak samo. Nie tłumacz pisowni — na razie tylko czytamy.",
                          "H i CH też brzmią tak samo. To samo podejście."],
            kiedy_dalej=["Dziecko czyta pięć wyrazów z dwuznakami bez rozkładania ich na litery.",
                         "Przeczytało czytankę bez zatrzymania na SZ i CZ."],
            jesli_nie_idzie=["Ćwicz jeden dwuznak przez trzy dni. SZ jest najłatwiejszy.",
                             "Podkreślaj dwuznaki ołówkiem przed czytaniem."]),
    ),
    # ---------------------------------------------------------------- 11
    dict(
        nr=11, poziom=11,
        cel="Dziecko czyta wyrazy, w których dwie spółgłoski stoją obok siebie.",
        litery=["R", "Ś", "Ć", "Ź", "Ń"],
        sylaby=syl("R") + ["BRA", "TRA", "KRA", "PRA", "DRA", "GRA",
                            "STA", "SKA", "PLA", "KLA", "ŚĆ", "ŚNI", "ĆMA"],
        wyrazy=["RAK", "RURA", "ROWER", "BRAT", "TRAWA", "DROGA",
                "KLASA", "PLECAK", "SKOK", "GRA", "KOŃ", "SIEĆ"],
        opis="R i zbiegi spółgłoskowe — dwie spółgłoski bez samogłoski między nimi. "
             "Plus litery miękkie z kreską: Ś, Ć, Ź, Ń.",
        powtorka_z=[9, 10], powtorka_syl=syl("SZ", "CZ") + syl("Z", "G"),
        powtorka_wyr=["SZAFA", "ŻABA", "MUCHA", "KOZA", "JAGODA"],
        zdania=["TO RAK.", "BRAT MA ROWER.", "W KLASIE JEST PLECAK.", "NA TRAWIE JEST RURA."],
        czytanka=dict(
            tytul="Brat ma rower", czyta="dziecko",
            linie=["TO RAK.", "BRAT MA ROWER.", "W KLASIE JEST PLECAK.",
                   "NA TRAWIE JEST RURA.", "BRAT I RAK."],
            pytania=["Co ma brat?", "Co jest w klasie?",
                     "Znajdź słowo, w którym dwie spółgłoski stoją obok siebie."]),
        gra=dict(
            nazwa="Zbieg spółgłosek",
            cel="Przeczytać dwie spółgłoski razem, bez wstawiania samogłoski.",
            gracze="2 osoby", czas=12,
            przygotowanie=["Wytnij karty ze zbiegami: BR, TR, KR, PR, DR, GR, ST, SK, PL, KL.",
                           "Wytnij karty z końcówkami: AT, AWA, OGA, ASA, OK."],
            zasady=["Losujesz kartę ze zbiegiem i kartę z końcówką.",
                    "Czytasz, co powstało. Czasem wyjdzie wyraz, czasem nie.",
                    "Za prawdziwy wyraz bierzesz punkt i zapisujesz go na kartce.",
                    "Gracie do dziesięciu punktów."],
            elementy=["10 kart ze zbiegami", "5 kart z końcówkami", "kartka na zapisywanie wyrazów"]),
        karta_rodzica=dict(
            co_powiedziec=["„BR to dwie spółgłoski razem. Nie mów BE-ER.”",
                           "„Spróbuj powiedzieć BRAT bez zatrzymania w środku.”",
                           "„Kreska nad literą zmienia dźwięk: S to S, a Ś to Ś.”"],
            na_co_uwazac=["Dziecko będzie wstawiać samogłoskę: BERAT zamiast BRAT. Powiedz wyraz szybko, żeby usłyszało.",
                          "R jest najtrudniejszą głoską i dziecko może jej jeszcze nie wymawiać. To nie przeszkadza w czytaniu.",
                          "Jeśli dziecko nie mówi R, czyta się je tak samo — nie poprawiaj wymowy przy czytaniu."],
            kiedy_dalej=["Dziecko czyta pięć wyrazów ze zbiegiem bez wstawiania samogłoski.",
                         "Rozróżnia S i Ś w tabeli."],
            jesli_nie_idzie=["Ćwicz najpierw zbiegi na końcu wyrazu, potem na początku.",
                             "Zostaw miękkie na tydzień 12, skup się na zbiegach."]),
    ),
    # ---------------------------------------------------------------- 12
    dict(
        nr=12, poziom=12,
        cel="Dziecko czyta samo ośmiostronicową książeczkę.",
        litery=["Ą", "Ę"], sylaby=["SĄ", "MĄ", "RĄ", "WĄ", "SĘ", "MĘ", "RĘ", "WĘ"],
        wyrazy=["SĄ", "MAJĄ", "IDĘ", "RĘKA", "WĄSY", "KSIĄŻKA"],
        opis="Nosowe Ą i Ę, a potem pełna powtórka i książeczka. Nowego materiału jest tu najmniej.",
        powtorka_z=[8, 9, 10, 11],
        powtorka_syl=syl("R") + ["AM", "OT", "EK"] + syl("SZ", "CZ"),
        powtorka_wyr=["KOT", "DOM", "SZAFA", "ŻABA", "BRAT", "ROWER", "JAGODA", "KOZA"],
        zdania=["KOT I SOWA SĄ W DOMU.", "IDĘ DO LASU.", "MAM KSIĄŻKĘ."],
        czytanka=dict(
            tytul="Koniec i początek", czyta="dziecko",
            linie=["TO JEST KONIEC.", "ALE TO JEST TEŻ POCZĄTEK.",
                   "UMIESZ JUŻ CZYTAĆ.", "TERAZ CZYTAJ, CO CHCESZ."],
            pytania=["Przeczytaj to komuś w domu.",
                     "Co chcesz przeczytać jako następne?"]),
        gra=dict(
            nazwa="Wielka powtórka",
            cel="Przeczytać wyraz z dowolnego tygodnia programu.",
            gracze="2–4 osoby", czas=20,
            przygotowanie=["Wytnij planszę z dwunastoma polami — po jednym na każdy tydzień.",
                           "Wytnij karty z wyrazami z całego programu."],
            zasady=["Rzucasz kostką i przesuwasz pionek.",
                    "Bierzesz kartę z wyrazem z tego tygodnia, na którym stanąłeś.",
                    "Czytasz wyraz. Jeśli się uda — zostajesz. Jeśli nie — cofasz się o jedno pole.",
                    "Wygrywa ten, kto pierwszy przejdzie wszystkie dwanaście tygodni."],
            elementy=["plansza 12 pól", "60 kart z wyrazami z tygodni 2–11",
                      "4 pionki", "kostka"]),
        karta_rodzica=dict(
            co_powiedziec=["„Przeczytaj tę książeczkę sam. Ja posłucham.”",
                           "„Nie musisz czytać szybko. Musisz przeczytać do końca.”",
                           "„Ą i Ę mają ogonek. Czytamy je przez nos.”"],
            na_co_uwazac=["Nie czytaj razem z dzieckiem. Ten tydzień jest po to, żeby zrobiło to samo.",
                          "Jeśli utknie na wyrazie, poczekaj pięć sekund, zanim pomożesz.",
                          "Książeczkę można czytać przez cały tydzień, po jednej stronie dziennie.",
                          "Po skończeniu programu wróćcie do czytanek z tygodni 5–8. Pójdą teraz płynnie."],
            kiedy_dalej=["Dziecko przeczytało całą książeczkę samo, choćby wolno.",
                         "To koniec programu. Następny krok to „Czytam i rozumiem”, ale nie od razu — "
                         "daj miesiąc na czytanie tego, co dziecko samo wybierze."],
            jesli_nie_idzie=["Przeczytaj książeczkę razem, a za dwa tygodnie poproś dziecko o samodzielne czytanie.",
                             "Wróć do tygodnia 8. Zwykle tam jest luka."]),
    ),
]

# Ośmiostronicowa książeczka z tygodnia 12 — po jednej stronie na kartkę.
KSIAZECZKA = [
    dict(tytul="Strona 1", zdania=["TO JEST KOT.", "KOT MA NA IMIE MRUK."]),
    dict(tytul="Strona 2", zdania=["MRUK MA DOM.", "DOM JEST MAŁY."]),
    dict(tytul="Strona 3", zdania=["OBOK DOMU JEST LAS.", "W LESIE JEST SOWA."]),
    dict(tytul="Strona 4", zdania=["SOWA MA NA IMIE UHU.", "UHU NIE SPI W NOCY."]),
    dict(tytul="Strona 5", zdania=["MRUK IDZIE DO LASU.", "SZUKA SOWY."]),
    dict(tytul="Strona 6", zdania=["UHU SIEDZI NA DRZEWIE.", "MRUK PATRZY W GORE."]),
    dict(tytul="Strona 7", zdania=["CZESC, UHU.", "CZESC, MRUK."]),
    dict(tytul="Strona 8", zdania=["TERAZ SĄ RAZEM.", "KONIEC."]),
]
